apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-dep
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      volumes:
        - name: shared-files
          persistentVolumeClaim:
            claimName: project-files-claim
      containers:
        - name: server
          image: SERVER/IMAGE
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "3001"
            - name: IMAGE_FILE_PATH
              value: "files/image.jpg"
            - name: TIMESTAMP_FILE_PATH
              value: "files/timestamp.txt"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: project-secrets
                  key: postgres-password
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: config-map-variables
                  key: nats-url
          volumeMounts:
            - name: shared-files
              mountPath: /usr/src/app/files
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 10
            httpGet:
              path: /healthz
              port: 3001
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 3001
          resources:
            requests:
              memory: '64Mi'
              cpu: '250m'
            limits:
              memory: '516Mi'
              cpu: '500m'

---

apiVersion: v1
kind: Service
metadata:
  name: server-svc
spec:
  type: NodePort
  selector:
    app: server
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3001
