apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map-variables
data:
  nats-url: "nats://my-nats:4222"
  create-daily-todo.sh: |-
    #!/usr/bin/env sh

    # Exit immediately if a command exits with a non-zero status.
    set -e

    echo "Posting the new TODO to $SERVER_URL"

    URL_GEN_OUTPUT=$(curl -sS -w "%{url_effective}\n" -I -L https://en.wikipedia.org/wiki/Special:Random -o /dev/null)
    URL_GEN_STATUS=$?

    if [ $URL_GEN_STATUS -eq 0 ]; then
      URL=$(echo "$URL_GEN_OUTPUT" | tail -n 1)
      echo "Generated random Wikipedia URL: $URL"
    else
      echo "Error: Failed to generate random Wikipedia URL (curl exit code: $URL_GEN_STATUS)." >&2
      echo "Curl error details: $URL_GEN_OUTPUT" >&2
      exit 1
    fi

    TODO_POST_RESPONSE=$(curl -s --show-error -X POST -H "Content-Type: application/json" -d '{"text": "<a href='${URL}' target=_blank>'${URL}'<a/>"}' "$SERVER_URL/api/todos")
    TODO_POST_STATUS=$?

    if [ $TODO_POST_STATUS -eq 0 ]; then
      echo "SUCCESS: New TODO posted successfully!"
    else
      echo "ERROR: Failed to post new TODO (curl exit code: $TODO_POST_STATUS)." >&2
      echo "Curl error details: $TODO_POST_RESPONSE" >&2
      exit 1
    fi
