services:
  client:
    image: client
    container_name: project-client
    build:
      context: .packages/client
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - REACT_APP_SERVER_URL=http://localhost:3001
    ports:
      - 3000:3000
  server:
    image: server
    container_name: project-server
    build:
      context: .packages/server
      dockerfile: Dockerfile
    environment:
      - PORT=3001
      - IMAGE_FILE_PATH="./shared/files/image.jpg"
      - TIMESTAMP_FILE_PATH="./shared/files/timestamp.txt"
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./shared/files:/usr/src/app/shared/files
    ports:
      - 3001:3001

  broadcaster:
    image: broadcaster
    container_name: broadcaster
    build:
      context: .packages/broadcaster
      dockerfile: Dockerfile

  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./database:/var/lib/postgresql/data


