import 'dotenv/config'

const { IMAGE_FILE_PATH, TIMESTAMP_FILE_PATH, PORT, POSTGRES_HOST, POSTGRES_PASSWORD, NATS_URL } = process.env

console.log('[SERVER]: Postgres config', {
  POSTGRES_HOST,
  NATS_URL,
})

export { IMAGE_FILE_PATH, TIMESTAMP_FILE_PATH, PORT, POSTGRES_HOST, POSTGRES_PASSWORD, NATS_URL }
